[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027CBB476010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8c3e29a9179d27e37ba6f23cf85a778e/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027CBB475450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8c3e29a9179d27e37ba6f23cf85a778e/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027CBB4769D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8c3e29a9179d27e37ba6f23cf85a778e/url